# Generated by Django 6.0 on 2025-12-15 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=200)),
                ('phone_number', models.CharField(default='N/A', max_length=20)),
                ('booth_id', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(choices=[('1p', 'Pavilion 1'), ('2p', 'Pavilion 2'), ('3p', 'Pavilion 3'), ('4p', 'Pavilion 4'), ('O', 'Outdoor')], max_length=2)),
                ('staff_type', models.CharField(choices=[('VIP', 'VIP'), ('Staff', 'Staff')], max_length=10)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='staff_qr/')),
                ('printed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('booth_id', models.CharField(max_length=100)),
                ('day_entered', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed', models.BooleanField(default=False)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='pass_qr/')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='entrance.staff')),
            ],
        ),
    ]
