# Generated by Django 6.0 on 2025-12-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='pass_qr/'),
        ),
    ]
