# Generated by Django 6.0 on 2025-12-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pass_photos/'),
        ),
        migrations.AddField(
            model_name='pass',
            name='photo_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
