# Generated by Django 6.0 on 2025-12-14 19:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0002_pass_qr_code_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['staff_code'], 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AddField(
            model_name='staff',
            name='booth_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staff',
            name='location',
            field=models.CharField(choices=[('1p', 'Pavilion 1'), ('2p', 'Pavilion 2'), ('3p', 'Pavilion 3'), ('4p', 'Pavilion 4'), ('O', 'Outdoor')], default='1p', max_length=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_code',
            field=models.CharField(default='TEMP_CODE', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('VIP', 'VIP (Owner)'), ('Sales', 'Sales Staff')], default='VIP', max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
