# Generated by Django 6.0 on 2025-12-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0002_pass_photo_pass_photo_taken_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_code_sheet',
            field=models.CharField(blank=True, help_text='Staff code from Excel/CSV (e.g. 1PV01, 1PS02)', max_length=20, null=True, unique=True),
        ),
    ]
