# Generated by Django 6.0 on 2025-12-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0003_alter_staff_options_staff_booth_id_staff_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='booth_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
