# Generated by Django 6.0 on 2025-12-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0003_staff_staff_code_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='sold',
            field=models.BooleanField(default=False, help_text="Whether this booth/staff slot is sold (from Excel 'Sold' column)."),
        ),
    ]
