# Generated by Django 6.0 on 2025-12-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0004_staff_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo for this staff/VIP', null=True, upload_to='staff_photos/'),
        ),
    ]
