# Generated by Django 6.0 on 2025-12-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0004_alter_staff_booth_id_alter_staff_staff_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['booth_id', 'name'], 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AddField(
            model_name='staff',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
