# Generated by Django 6.0 on 2025-12-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0005_alter_staff_options_staff_printed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['booth_id', 'staff_type', 'name'], 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AddField(
            model_name='pass',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
