# Generated by Django 6.0 on 2025-12-15 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0006_alter_staff_options_pass_printed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['booth_id', 'staff_type', 'name']},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='printed',
        ),
        migrations.AlterField(
            model_name='pass',
            name='day_entered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
