# Generated by Django 6.0 on 2025-12-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0007_alter_staff_options_remove_staff_printed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['booth_id']},
        ),
        migrations.AlterField(
            model_name='pass',
            name='day_entered',
            field=models.DateField(),
        ),
    ]
